// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: administration.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countAdmins = `-- name: CountAdmins :one
SELECT COUNT(*)
FROM administration
WHERE deleted_at IS NULL
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO administration (
    full_name,
    username,
    password
) VALUES (
    $1, $2, $3
) RETURNING id, full_name, username, password, created_at, updated_at, deleted_at
`

type CreateAdminParams struct {
	FullName string `json:"full_name"`
	Username string `json:"username"`
	Password string `json:"password"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (Administration, error) {
	row := q.db.QueryRow(ctx, createAdmin, arg.FullName, arg.Username, arg.Password)
	var i Administration
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, full_name, username, password, created_at, updated_at, deleted_at
FROM administration
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetAdminByID(ctx context.Context, id uuid.UUID) (Administration, error) {
	row := q.db.QueryRow(ctx, getAdminByID, id)
	var i Administration
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAdminByUsername = `-- name: GetAdminByUsername :one
SELECT id, full_name, username, password, created_at, updated_at, deleted_at
FROM administration
WHERE username = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetAdminByUsername(ctx context.Context, username string) (Administration, error) {
	row := q.db.QueryRow(ctx, getAdminByUsername, username)
	var i Administration
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAdmins = `-- name: ListAdmins :many
SELECT id, full_name, username, password, created_at, updated_at, deleted_at
FROM administration
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAdminsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAdmins(ctx context.Context, arg ListAdminsParams) ([]Administration, error) {
	rows, err := q.db.Query(ctx, listAdmins, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Administration{}
	for rows.Next() {
		var i Administration
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Username,
			&i.Password,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAdmin = `-- name: SoftDeleteAdmin :exec
UPDATE administration
SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteAdmin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteAdmin, id)
	return err
}

const updateAdmin = `-- name: UpdateAdmin :one
UPDATE administration
SET
    full_name  = COALESCE($2, full_name),
    username   = COALESCE($3, username),
    password   = COALESCE($4, password),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, full_name, username, password, created_at, updated_at, deleted_at
`

type UpdateAdminParams struct {
	ID       uuid.UUID `json:"id"`
	FullName string    `json:"full_name"`
	Username string    `json:"username"`
	Password string    `json:"password"`
}

func (q *Queries) UpdateAdmin(ctx context.Context, arg UpdateAdminParams) (Administration, error) {
	row := q.db.QueryRow(ctx, updateAdmin,
		arg.ID,
		arg.FullName,
		arg.Username,
		arg.Password,
	)
	var i Administration
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
