// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: couriers.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCouriers = `-- name: CountCouriers :one
SELECT COUNT(*)
FROM couriers
WHERE deleted_at IS NULL
`

func (q *Queries) CountCouriers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCouriers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const courierExists = `-- name: CourierExists :one
SELECT EXISTS (
    SELECT 1
    FROM couriers
    WHERE id = $1
      AND deleted_at IS NULL
)
`

func (q *Queries) CourierExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, courierExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createCourier = `-- name: CreateCourier :one
INSERT INTO couriers (
    id,
    full_name,
    phone,
    password,
    hired_at
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, full_name, phone, password, hired_at, is_active, created_at, updated_at, deleted_at
`

type CreateCourierParams struct {
	ID       uuid.UUID `json:"id"`
	FullName string    `json:"full_name"`
	Phone    string    `json:"phone"`
	Password string    `json:"password"`
	HiredAt  time.Time `json:"hired_at"`
}

func (q *Queries) CreateCourier(ctx context.Context, arg CreateCourierParams) (Courier, error) {
	row := q.db.QueryRow(ctx, createCourier,
		arg.ID,
		arg.FullName,
		arg.Phone,
		arg.Password,
		arg.HiredAt,
	)
	var i Courier
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Password,
		&i.HiredAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCourierByID = `-- name: GetCourierByID :one
SELECT id, full_name, phone, password, hired_at, is_active, created_at, updated_at, deleted_at
FROM couriers
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetCourierByID(ctx context.Context, id uuid.UUID) (Courier, error) {
	row := q.db.QueryRow(ctx, getCourierByID, id)
	var i Courier
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Password,
		&i.HiredAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCourierByPhone = `-- name: GetCourierByPhone :one
SELECT id, full_name, phone, password, hired_at, is_active, created_at, updated_at, deleted_at
FROM couriers
WHERE phone = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetCourierByPhone(ctx context.Context, phone string) (Courier, error) {
	row := q.db.QueryRow(ctx, getCourierByPhone, phone)
	var i Courier
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Password,
		&i.HiredAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCouriers = `-- name: ListCouriers :many
SELECT id, full_name, phone, password, hired_at, is_active, created_at, updated_at, deleted_at
FROM couriers
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListCouriersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCouriers(ctx context.Context, arg ListCouriersParams) ([]Courier, error) {
	rows, err := q.db.Query(ctx, listCouriers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Courier{}
	for rows.Next() {
		var i Courier
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Phone,
			&i.Password,
			&i.HiredAt,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCourier = `-- name: SoftDeleteCourier :exec
UPDATE couriers
SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCourier(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteCourier, id)
	return err
}

const updateCourier = `-- name: UpdateCourier :one
UPDATE couriers
SET
    full_name  = COALESCE($1, full_name),
    phone      = COALESCE($2, phone),
    password   = COALESCE($3, password),
    hired_at   = COALESCE($4, hired_at),
    is_active  = COALESCE($5, is_active),
    updated_at = NOW()
WHERE id = $6
  AND deleted_at IS NULL
RETURNING id, full_name, phone, password, hired_at, is_active, created_at, updated_at, deleted_at
`

type UpdateCourierParams struct {
	FullName *string     `json:"full_name"`
	Phone    *string     `json:"phone"`
	Password *string     `json:"password"`
	HiredAt  pgtype.Date `json:"hired_at"`
	IsActive *bool       `json:"is_active"`
	ID       uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateCourier(ctx context.Context, arg UpdateCourierParams) (Courier, error) {
	row := q.db.QueryRow(ctx, updateCourier,
		arg.FullName,
		arg.Phone,
		arg.Password,
		arg.HiredAt,
		arg.IsActive,
		arg.ID,
	)
	var i Courier
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Password,
		&i.HiredAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
