// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locks.sql

package sqlc

import (
	"context"
)

const advisoryUnlock = `-- name: AdvisoryUnlock :one
SELECT pg_advisory_unlock($1::bigint)
`

func (q *Queries) AdvisoryUnlock(ctx context.Context, key int64) (bool, error) {
	row := q.db.QueryRow(ctx, advisoryUnlock, key)
	var pg_advisory_unlock bool
	err := row.Scan(&pg_advisory_unlock)
	return pg_advisory_unlock, err
}

const tryAdvisoryLock = `-- name: TryAdvisoryLock :one
SELECT pg_try_advisory_lock($1::bigint)
`

func (q *Queries) TryAdvisoryLock(ctx context.Context, key int64) (bool, error) {
	row := q.db.QueryRow(ctx, tryAdvisoryLock, key)
	var pg_try_advisory_lock bool
	err := row.Scan(&pg_try_advisory_lock)
	return pg_try_advisory_lock, err
}
