// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countOrders = `-- name: CountOrders :one
SELECT COUNT(*)
FROM orders
WHERE ($1::uuid IS NULL OR courier_id = $1::uuid)
    AND ($2::order_status IS NULL OR status = $2::order_status)
    AND ($3::timestamptz IS NULL OR delivered_at >= $3::timestamptz)
    AND ($4::timestamptz   IS NULL OR delivered_at <  $4::timestamptz)
    AND ($5::timestamptz   IS NULL OR created_at   >= $5::timestamptz)
    AND ($6::timestamptz     IS NULL OR created_at   <  $6::timestamptz)
    AND ($7::numeric IS NULL OR amount >= $7::numeric)
    AND ($8::numeric IS NULL OR amount <= $8::numeric)
`

type CountOrdersParams struct {
	CourierID     *uuid.UUID     `json:"courier_id"`
	Status        *OrderStatus   `json:"status"`
	DeliveredFrom *time.Time     `json:"delivered_from"`
	DeliveredTo   *time.Time     `json:"delivered_to"`
	CreatedFrom   *time.Time     `json:"created_from"`
	CreatedTo     *time.Time     `json:"created_to"`
	AmountMin     pgtype.Numeric `json:"amount_min"`
	AmountMax     pgtype.Numeric `json:"amount_max"`
}

func (q *Queries) CountOrders(ctx context.Context, arg CountOrdersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrders,
		arg.CourierID,
		arg.Status,
		arg.DeliveredFrom,
		arg.DeliveredTo,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.AmountMin,
		arg.AmountMax,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    id,
    courier_id,
    amount
) VALUES (
    $1, $2, $3
) RETURNING id, courier_id, amount, status, delivered_at, created_at, updated_at
`

type CreateOrderParams struct {
	ID        uuid.UUID      `json:"id"`
	CourierID uuid.UUID      `json:"courier_id"`
	Amount    pgtype.Numeric `json:"amount"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.ID, arg.CourierID, arg.Amount)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CourierID,
		&i.Amount,
		&i.Status,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrder = `-- name: DeleteOrder :exec
DELETE FROM orders
WHERE id = $1
`

func (q *Queries) DeleteOrder(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrder, id)
	return err
}

const getDeliveredStatsForPeriod = `-- name: GetDeliveredStatsForPeriod :one
SELECT
    COUNT(*)::bigint                  AS delivered_count,
    COALESCE(SUM(amount), 0)::numeric AS delivered_total
FROM orders
WHERE courier_id = $1
  AND status = 'delivered'
  AND delivered_at >= $2::timestamptz
  AND delivered_at <  $3::timestamptz
`

type GetDeliveredStatsForPeriodParams struct {
	CourierID   uuid.UUID `json:"courier_id"`
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
}

type GetDeliveredStatsForPeriodRow struct {
	DeliveredCount int64          `json:"delivered_count"`
	DeliveredTotal pgtype.Numeric `json:"delivered_total"`
}

func (q *Queries) GetDeliveredStatsForPeriod(ctx context.Context, arg GetDeliveredStatsForPeriodParams) (GetDeliveredStatsForPeriodRow, error) {
	row := q.db.QueryRow(ctx, getDeliveredStatsForPeriod, arg.CourierID, arg.PeriodStart, arg.PeriodEnd)
	var i GetDeliveredStatsForPeriodRow
	err := row.Scan(&i.DeliveredCount, &i.DeliveredTotal)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, courier_id, amount, status, delivered_at, created_at, updated_at
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CourierID,
		&i.Amount,
		&i.Status,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByIDForUpdate = `-- name: GetOrderByIDForUpdate :one
SELECT id, courier_id, amount, status, delivered_at, created_at, updated_at
FROM orders
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetOrderByIDForUpdate(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByIDForUpdate, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CourierID,
		&i.Amount,
		&i.Status,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrders = `-- name: ListOrders :many
SELECT id, courier_id, amount, status, delivered_at, created_at, updated_at
FROM orders
WHERE ($1::uuid IS NULL OR courier_id = $1::uuid)
    AND ($2::order_status IS NULL OR status = $2::order_status)
    AND ($3::timestamptz IS NULL OR delivered_at >= $3::timestamptz)
    AND ($4::timestamptz   IS NULL OR delivered_at <  $4::timestamptz)
    AND ($5::timestamptz   IS NULL OR created_at   >= $5::timestamptz)
    AND ($6::timestamptz     IS NULL OR created_at   <  $6::timestamptz)
    AND ($7::numeric IS NULL OR amount >= $7::numeric)
    AND ($8::numeric IS NULL OR amount <= $8::numeric)
ORDER BY
    CASE WHEN $9::text = 'amount'       AND $10::text = 'asc'  THEN amount       END ASC,
    CASE WHEN $9::text = 'amount'       AND $10::text = 'desc' THEN amount       END DESC,
    CASE WHEN $9::text = 'delivered_at' AND $10::text = 'asc'  THEN delivered_at END ASC,
    CASE WHEN $9::text = 'delivered_at' AND $10::text = 'desc' THEN delivered_at END DESC,
    CASE WHEN $9::text = 'created_at'   AND $10::text = 'asc'  THEN created_at   END ASC,
    created_at DESC
LIMIT $12::int
OFFSET $11::int
`

type ListOrdersParams struct {
	CourierID     *uuid.UUID     `json:"courier_id"`
	Status        *OrderStatus   `json:"status"`
	DeliveredFrom *time.Time     `json:"delivered_from"`
	DeliveredTo   *time.Time     `json:"delivered_to"`
	CreatedFrom   *time.Time     `json:"created_from"`
	CreatedTo     *time.Time     `json:"created_to"`
	AmountMin     pgtype.Numeric `json:"amount_min"`
	AmountMax     pgtype.Numeric `json:"amount_max"`
	SortBy        string         `json:"sort_by"`
	SortDir       string         `json:"sort_dir"`
	Offset        int32          `json:"offset"`
	Limit         int32          `json:"limit"`
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders,
		arg.CourierID,
		arg.Status,
		arg.DeliveredFrom,
		arg.DeliveredTo,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.AmountMin,
		arg.AmountMax,
		arg.SortBy,
		arg.SortDir,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CourierID,
			&i.Amount,
			&i.Status,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET
    status       = $1,
    delivered_at = CASE
                       WHEN $1::order_status = 'delivered' THEN NOW()
                       ELSE delivered_at
                   END,
    updated_at   = NOW()
WHERE id = $2
RETURNING id, courier_id, amount, status, delivered_at, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	Status OrderStatus `json:"status"`
	ID     uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.Status, arg.ID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CourierID,
		&i.Amount,
		&i.Status,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
