// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payouts.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPayouts = `-- name: CountPayouts :one
SELECT COUNT(*)
FROM payouts
WHERE ($1::uuid IS NULL OR courier_id = $1::uuid)
  AND ($2::payout_status IS NULL OR status = $2::payout_status)
  AND ($3::date IS NULL OR period >= $3::date)
  AND ($4::date   IS NULL OR period <= $4::date)
`

type CountPayoutsParams struct {
	CourierID  *uuid.UUID    `json:"courier_id"`
	Status     *PayoutStatus `json:"status"`
	PeriodFrom *time.Time    `json:"period_from"`
	PeriodTo   *time.Time    `json:"period_to"`
}

func (q *Queries) CountPayouts(ctx context.Context, arg CountPayoutsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPayouts,
		arg.CourierID,
		arg.Status,
		arg.PeriodFrom,
		arg.PeriodTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPayout = `-- name: CreatePayout :one
INSERT INTO payouts (
    id,
    courier_id,
    period,
    delivered_count,
    gross_amount,
    commission_rate,
    commission_amount,
    net_amount
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, courier_id, period, delivered_count, gross_amount, commission_rate, commission_amount, net_amount, status, calculated_at, paid_at, created_at, updated_at
`

type CreatePayoutParams struct {
	ID               uuid.UUID      `json:"id"`
	CourierID        uuid.UUID      `json:"courier_id"`
	Period           time.Time      `json:"period"`
	DeliveredCount   int32          `json:"delivered_count"`
	GrossAmount      pgtype.Numeric `json:"gross_amount"`
	CommissionRate   pgtype.Numeric `json:"commission_rate"`
	CommissionAmount pgtype.Numeric `json:"commission_amount"`
	NetAmount        pgtype.Numeric `json:"net_amount"`
}

func (q *Queries) CreatePayout(ctx context.Context, arg CreatePayoutParams) (Payout, error) {
	row := q.db.QueryRow(ctx, createPayout,
		arg.ID,
		arg.CourierID,
		arg.Period,
		arg.DeliveredCount,
		arg.GrossAmount,
		arg.CommissionRate,
		arg.CommissionAmount,
		arg.NetAmount,
	)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.CourierID,
		&i.Period,
		&i.DeliveredCount,
		&i.GrossAmount,
		&i.CommissionRate,
		&i.CommissionAmount,
		&i.NetAmount,
		&i.Status,
		&i.CalculatedAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPayoutByCourierPeriod = `-- name: GetPayoutByCourierPeriod :one
SELECT id, courier_id, period, delivered_count, gross_amount, commission_rate, commission_amount, net_amount, status, calculated_at, paid_at, created_at, updated_at
FROM payouts
WHERE courier_id = $1
  AND period = $2
`

type GetPayoutByCourierPeriodParams struct {
	CourierID uuid.UUID `json:"courier_id"`
	Period    time.Time `json:"period"`
}

func (q *Queries) GetPayoutByCourierPeriod(ctx context.Context, arg GetPayoutByCourierPeriodParams) (Payout, error) {
	row := q.db.QueryRow(ctx, getPayoutByCourierPeriod, arg.CourierID, arg.Period)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.CourierID,
		&i.Period,
		&i.DeliveredCount,
		&i.GrossAmount,
		&i.CommissionRate,
		&i.CommissionAmount,
		&i.NetAmount,
		&i.Status,
		&i.CalculatedAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPayoutByID = `-- name: GetPayoutByID :one
SELECT id, courier_id, period, delivered_count, gross_amount, commission_rate, commission_amount, net_amount, status, calculated_at, paid_at, created_at, updated_at
FROM payouts
WHERE id = $1
`

func (q *Queries) GetPayoutByID(ctx context.Context, id uuid.UUID) (Payout, error) {
	row := q.db.QueryRow(ctx, getPayoutByID, id)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.CourierID,
		&i.Period,
		&i.DeliveredCount,
		&i.GrossAmount,
		&i.CommissionRate,
		&i.CommissionAmount,
		&i.NetAmount,
		&i.Status,
		&i.CalculatedAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPayouts = `-- name: ListPayouts :many
SELECT id, courier_id, period, delivered_count, gross_amount, commission_rate, commission_amount, net_amount, status, calculated_at, paid_at, created_at, updated_at
FROM payouts
WHERE ($1::uuid IS NULL OR courier_id = $1::uuid)
  AND ($2::payout_status IS NULL OR status = $2::payout_status)
  AND ($3::date IS NULL OR period >= $3::date)
  AND ($4::date   IS NULL OR period <= $4::date)
ORDER BY
    CASE WHEN $5::text = 'period'     AND $6::text = 'asc'  THEN period     END ASC,
    CASE WHEN $5::text = 'period'     AND $6::text = 'desc' THEN period     END DESC,
    CASE WHEN $5::text = 'net_amount' AND $6::text = 'asc'  THEN net_amount END ASC,
    CASE WHEN $5::text = 'net_amount' AND $6::text = 'desc' THEN net_amount END DESC,
    CASE WHEN $5::text = 'created_at' AND $6::text = 'asc'  THEN created_at END ASC,
    created_at DESC
LIMIT $8::int
OFFSET $7::int
`

type ListPayoutsParams struct {
	CourierID  *uuid.UUID    `json:"courier_id"`
	Status     *PayoutStatus `json:"status"`
	PeriodFrom *time.Time    `json:"period_from"`
	PeriodTo   *time.Time    `json:"period_to"`
	SortBy     string        `json:"sort_by"`
	SortDir    string        `json:"sort_dir"`
	Offset     int32         `json:"offset"`
	Limit      int32         `json:"limit"`
}

func (q *Queries) ListPayouts(ctx context.Context, arg ListPayoutsParams) ([]Payout, error) {
	rows, err := q.db.Query(ctx, listPayouts,
		arg.CourierID,
		arg.Status,
		arg.PeriodFrom,
		arg.PeriodTo,
		arg.SortBy,
		arg.SortDir,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payout{}
	for rows.Next() {
		var i Payout
		if err := rows.Scan(
			&i.ID,
			&i.CourierID,
			&i.Period,
			&i.DeliveredCount,
			&i.GrossAmount,
			&i.CommissionRate,
			&i.CommissionAmount,
			&i.NetAmount,
			&i.Status,
			&i.CalculatedAt,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePayoutStatus = `-- name: UpdatePayoutStatus :one
UPDATE payouts
SET
    status     = $1,
    paid_at    = CASE
                     WHEN $1::payout_status = 'paid' THEN NOW()
                     ELSE paid_at
                 END,
    updated_at = NOW()
WHERE id = $2
RETURNING id, courier_id, period, delivered_count, gross_amount, commission_rate, commission_amount, net_amount, status, calculated_at, paid_at, created_at, updated_at
`

type UpdatePayoutStatusParams struct {
	Status PayoutStatus `json:"status"`
	ID     uuid.UUID    `json:"id"`
}

func (q *Queries) UpdatePayoutStatus(ctx context.Context, arg UpdatePayoutStatusParams) (Payout, error) {
	row := q.db.QueryRow(ctx, updatePayoutStatus, arg.Status, arg.ID)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.CourierID,
		&i.Period,
		&i.DeliveredCount,
		&i.GrossAmount,
		&i.CommissionRate,
		&i.CommissionAmount,
		&i.NetAmount,
		&i.Status,
		&i.CalculatedAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
