// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payout_adjustments.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPayoutAdjustments = `-- name: CountPayoutAdjustments :one
SELECT COUNT(*)
FROM payout_adjustments
WHERE ($1::uuid IS NULL OR payout_id = $1::uuid)
  AND ($2::uuid  IS NULL OR order_id  = $2::uuid)
  AND ($3::adjustment_type IS NULL OR type = $3::adjustment_type)
  AND ($4::timestamptz IS NULL OR created_at >= $4::timestamptz)
  AND ($5::timestamptz   IS NULL OR created_at <  $5::timestamptz)
`

type CountPayoutAdjustmentsParams struct {
	PayoutID    uuid.UUID       `json:"payout_id"`
	OrderID     uuid.UUID       `json:"order_id"`
	Type        *AdjustmentType `json:"type"`
	CreatedFrom *time.Time      `json:"created_from"`
	CreatedTo   *time.Time      `json:"created_to"`
}

func (q *Queries) CountPayoutAdjustments(ctx context.Context, arg CountPayoutAdjustmentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPayoutAdjustments,
		arg.PayoutID,
		arg.OrderID,
		arg.Type,
		arg.CreatedFrom,
		arg.CreatedTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPayoutAdjustment = `-- name: CreatePayoutAdjustment :one
INSERT INTO payout_adjustments (
    id,
    payout_id,
    order_id,
    type,
    gross_delta,
    commission_delta,
    net_delta,
    reason
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, payout_id, order_id, type, gross_delta, commission_delta, net_delta, reason, created_at
`

type CreatePayoutAdjustmentParams struct {
	ID              uuid.UUID      `json:"id"`
	PayoutID        uuid.UUID      `json:"payout_id"`
	OrderID         uuid.UUID      `json:"order_id"`
	Type            AdjustmentType `json:"type"`
	GrossDelta      pgtype.Numeric `json:"gross_delta"`
	CommissionDelta pgtype.Numeric `json:"commission_delta"`
	NetDelta        pgtype.Numeric `json:"net_delta"`
	Reason          *string        `json:"reason"`
}

func (q *Queries) CreatePayoutAdjustment(ctx context.Context, arg CreatePayoutAdjustmentParams) (PayoutAdjustment, error) {
	row := q.db.QueryRow(ctx, createPayoutAdjustment,
		arg.ID,
		arg.PayoutID,
		arg.OrderID,
		arg.Type,
		arg.GrossDelta,
		arg.CommissionDelta,
		arg.NetDelta,
		arg.Reason,
	)
	var i PayoutAdjustment
	err := row.Scan(
		&i.ID,
		&i.PayoutID,
		&i.OrderID,
		&i.Type,
		&i.GrossDelta,
		&i.CommissionDelta,
		&i.NetDelta,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const getPayoutAdjustmentByID = `-- name: GetPayoutAdjustmentByID :one
SELECT id, payout_id, order_id, type, gross_delta, commission_delta, net_delta, reason, created_at
FROM payout_adjustments
WHERE id = $1
`

func (q *Queries) GetPayoutAdjustmentByID(ctx context.Context, id uuid.UUID) (PayoutAdjustment, error) {
	row := q.db.QueryRow(ctx, getPayoutAdjustmentByID, id)
	var i PayoutAdjustment
	err := row.Scan(
		&i.ID,
		&i.PayoutID,
		&i.OrderID,
		&i.Type,
		&i.GrossDelta,
		&i.CommissionDelta,
		&i.NetDelta,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const listPayoutAdjustments = `-- name: ListPayoutAdjustments :many
SELECT id, payout_id, order_id, type, gross_delta, commission_delta, net_delta, reason, created_at
FROM payout_adjustments
WHERE ($1::uuid IS NULL OR payout_id = $1::uuid)
  AND ($2::uuid  IS NULL OR order_id  = $2::uuid)
  AND ($3::adjustment_type IS NULL OR type = $3::adjustment_type)
  AND ($4::timestamptz IS NULL OR created_at >= $4::timestamptz)
  AND ($5::timestamptz   IS NULL OR created_at <  $5::timestamptz)
ORDER BY
    CASE WHEN $6::text = 'created_at' AND $7::text = 'asc' THEN created_at END ASC,
    created_at DESC
LIMIT $9::int
OFFSET $8::int
`

type ListPayoutAdjustmentsParams struct {
	PayoutID    uuid.UUID       `json:"payout_id"`
	OrderID     uuid.UUID       `json:"order_id"`
	Type        *AdjustmentType `json:"type"`
	CreatedFrom *time.Time      `json:"created_from"`
	CreatedTo   *time.Time      `json:"created_to"`
	SortBy      string          `json:"sort_by"`
	SortDir     string          `json:"sort_dir"`
	Offset      int32           `json:"offset"`
	Limit       int32           `json:"limit"`
}

func (q *Queries) ListPayoutAdjustments(ctx context.Context, arg ListPayoutAdjustmentsParams) ([]PayoutAdjustment, error) {
	rows, err := q.db.Query(ctx, listPayoutAdjustments,
		arg.PayoutID,
		arg.OrderID,
		arg.Type,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.SortBy,
		arg.SortDir,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PayoutAdjustment{}
	for rows.Next() {
		var i PayoutAdjustment
		if err := rows.Scan(
			&i.ID,
			&i.PayoutID,
			&i.OrderID,
			&i.Type,
			&i.GrossDelta,
			&i.CommissionDelta,
			&i.NetDelta,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayoutAdjustmentsByPayoutID = `-- name: ListPayoutAdjustmentsByPayoutID :many
SELECT id, payout_id, order_id, type, gross_delta, commission_delta, net_delta, reason, created_at
FROM payout_adjustments
WHERE payout_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListPayoutAdjustmentsByPayoutID(ctx context.Context, payoutID uuid.UUID) ([]PayoutAdjustment, error) {
	rows, err := q.db.Query(ctx, listPayoutAdjustmentsByPayoutID, payoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PayoutAdjustment{}
	for rows.Next() {
		var i PayoutAdjustment
		if err := rows.Scan(
			&i.ID,
			&i.PayoutID,
			&i.OrderID,
			&i.Type,
			&i.GrossDelta,
			&i.CommissionDelta,
			&i.NetDelta,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
