// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package administration

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Administration struct {
	ID        pgtype.UUID        `json:"id"`
	FullName  string             `json:"full_name"`
	Username  string             `json:"username"`
	Password  string             `json:"password"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt time.Time          `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}
